### ISSUE TITLE
All subpages on https://openrisc.github.io/ result in "404 - not found"

### ISSUE THREAD

**Issue by Olf0** [openrisc/openrisc.github.io#14]
Currently (as of 2019-10-15) all subpages on https://openrisc.github.io/ result in "404 - not found", i.e. solely the front-/home-page works (for me).

As the MD-files in this repository are fine, this may be a configuration- or CI/CD-flaw.

HTH

**Comment by wallento** [comment]
Thanks for reporting, it was a server misconfiguration which is fixed now.
