### ISSUE TITLE
Fill empty implementation sections in soc.md

### ISSUE THREAD

**Issue by Olf0** [openrisc/openrisc.github.io#16]
#### Issue:
Many of the implementations sections in [*soc.md*](https://github.com/openrisc/openrisc.github.io/blob/master/soc.md) are empty.
Consequently the corresponding links in the ["System-on-chip" section of *index.md*](https://github.com/openrisc/openrisc.github.io/blob/master/index.md#system-on-chip) are practically broken: They point to an anchor within an empty section, hence appearing to link to another, wrong section!

#### Suggested solution:
See MR #15 
<br />
P.S. / side note:
You may consider to close issues #9 and #10, because they appear to be opened without fully comprehending the focus and state of the OpenRISC "ecosystem".

**Comment by Olf0** [comment]
Thanks @stffrdhrn for merging PR #15 per commit [#29a0474](https://github.com/openrisc/openrisc.github.io/commit/29a0474225074b595f7bab8901e592d452f1bc3b).

P.S.: You may still consider [the "P.S. / side note" of the original message](https://github.com/openrisc/openrisc.github.io/issues/16#issue-585793183) of this thread / issue.

**Comment by stffrdhrn** [comment]
Thanks for your comments. Sorry I'm really sorry to see them.
