### ISSUE TITLE
[Suggestion] Add a clear list and on menu, with all hardwares you produce and how to order them

### ISSUE THREAD

**Issue by danimesq** [openrisc/openrisc.github.io#9]

**Comment by stffrdhrn** [comment]
There is no provided hardware that we produce, some big companies build parts but not that are publicly available or advertised.

**Comment by jeremybennett** [comment]
However, if you want to see a selection of products that have used OpenRISC IP, you can look on the Wikipedia page: https://en.wikipedia.org/wiki/OpenRISC

**Comment by stffrdhrn** [comment]
On Wed, Jun 05, 2019 at 11:48:15PM -0700, Jeremy Bennett wrote:
>However, if you want to see a selection of products that have used OpenRISC IP, you can look on the Wikipedia page: https://en.wikipedia.org/wiki/OpenRISC

Good point.  Either we can link to the wiki page or keep a list of our own.  I
would not know what to include in the full list though.

**Comment by stffrdhrn** [comment]
Closing as soc page covers this.
